workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.oasistaxis.app
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.oasistaxis.app \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --project=app/ios/Runner.xcodeproj
      - name: Get Flutter packages
        script: |
          cd app && flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd app/ios && pod install
      - name: Flutter build iOS
        script: |
          cd app && flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
